import mongoose from 'mongoose';

export const CHAT_MAX_LENGTH = 1000;
// Messages are deleted when their meeting ends (see meeting.service endMeeting).
// This TTL is only a backstop for meetings that are never explicitly ended.
export const MESSAGE_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

const messageSchema = new mongoose.Schema(
  {
    meetingId: { type: mongoose.Schema.Types.ObjectId, ref: 'Meeting', required: true },
    participantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Participant', required: true },
    // Denormalized so history loads with one query and no join.
    senderName: { type: String, required: true },
    text: { type: String, required: true, maxlength: CHAT_MAX_LENGTH },
    // Generated by the sender; makes retries idempotent (no duplicate messages).
    clientMsgId: { type: String, required: true },
    expiresAt: {
      type: Date,
      default: () => new Date(Date.now() + MESSAGE_RETENTION_MS),
      index: { expireAfterSeconds: 0 },
    },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

// History for one meeting, newest first.
messageSchema.index({ meetingId: 1, createdAt: -1 });
// A participant can't store the same clientMsgId twice.
messageSchema.index({ participantId: 1, clientMsgId: 1 }, { unique: true });

messageSchema.methods.toPublic = function toPublic() {
  return {
    id: this.id,
    participantId: this.participantId.toString(),
    senderName: this.senderName,
    text: this.text,
    clientMsgId: this.clientMsgId,
    createdAt: this.createdAt.toISOString(),
  };
};

export const Message = mongoose.model('Message', messageSchema);
